# GENERATED FILE DONT TOUCH THES SHET
name: Update game client

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: free disk space
        run: |
          df -h
          # sudo swapoff -a
          # sudo rm -f /swapfile
          # sudo apt clean
          # docker rmi $(docker image ls -aq)
          sudo swapoff -a
          # sudo swapoff /swapfile
          sudo rm -rf /swapfile /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h
